name: Run pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: setup setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.14'
    
    - name: Install pre-commit framework
      env:
        PRE_COMMIT_VERSION: 3.7.1
      run: |
        pip install pre-commit==${PRE_COMMIT_VERSION}
        pre-commit --version

    - name: Run pre-commit
      run: pre-commit run --all-files --verbose --show-diff-on-failure --color=auto
      
