name: test-action
on:
    pull_request:
    push:
        branches: [main]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - name: add go to path
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.5'
    - name: Get Release
      id: get_release
      uses: gamethis/get_latest_release_action@v1
      with:
        repo: get_latest_release_action
    - name: Get the output time
      run: echo "The time was ${{ steps.get_release.outputs.version }}"
