name: test-action
on:
    pull_request:
    push:
        branches: [main]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: gamethis/get_latest_release_action
      with:
        repo: get_latest_release_action
